steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/testing-iqbal:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/testing-iqbal:$COMMIT_SHA'
images:
  - 'gcr.io/$PROJECT_ID/testing-iqbal:$COMMIT_SHA'
logsBucket: 'gs://bangkitcapstone-bloomy-bucket/logs'